/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:37cc05ce-1570-4a46-9ee3-1b958ee16ec7",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_DE5l2AC1p",
    "aws_user_pools_web_client_id": "5aa0smbjmptssirkme669ad4gt",
    "oauth": {}
};


export default awsmobile;
